#+Title: Pilot Workshop at GMRIT, Srikakulam
#+Author: VLEAD

* Objective of the workshop
  - College Cloud should be able to serve the labs to the students
    to perform experiments or to use the labs without the Internet
    connection.

  - Conduct the workshop offline using portable-media.

  - Note down the issues if there are any, during the workshop and
    report the issues to =engg@vlabs.ac.in=

* Introduction on Pilot Test
** Introduction
   Introduction about Portable-media
   + What is Portable-Media?
** Demo Lab
   - =Image Processing Lab=
** Limitations
   - 15-20 students in one run
** Number of Students and Workshop duration 
   Let's say, for example, 20 students per 30 mins, so for 100
   students=5 groups, 5*30mins= 150mins= 2 hrs 30 mins
** How many labs at a time + Which Labs?   
  - Two labs at a time 
    + Problem solving (cse04-iiith.vlabs.a.cin)
    + Image Processing (cse19-iiith.vlabs.ac.in)
** Feedback collection with reference to portable media 
   After the workshop, collecting feedbacks and analytics on
   portable-media.

* Pilot workshop details
** 9th Jan 2017 - afternoon
   Took Xenon server 
   Copied college cloud to GMRIT's 500GB SATA HDD
** 10th Jan 2017 
*** Morning session 10:00AM to 12:00 PM
    - Took the machine
    - Attached GMRIT's 500 GB SATS HDD college cloud
    - Connected wifi routers LAN port to the machine
    - Booted the machine
    - Tested one lab with the college cloud - It was working
   
    - I have taken five IPs from GMRIT network. These ips will be used
      for college cloud setup. So that, every one can access virtual
      labs over LAN. I have configured college cloud with the five
      ips.
      - I have taken client machine to test college cloud in the same
        LAN.
      - Open edX platform was opening but lab was opening very slow.
      - Then I went to the other place where workshop is going
	on. Open edX platform was not opening

    - I thought of using normal computer that is there in workshop lab
      - It has very less system configuration
	- RAM : 4GB ( which is not enough for our college cloud)
    - They could not bring other machine that has better system
      configuration

    - Finally, I used my lap top
      #+BEGIN_EXAMPLE
      RAM : 8GB ( 4 GB for Open-edX platform, 4GB for host machine)
      CPUs:4  ( 2 for Open-edX platform, 2 for Host machine( cluster))
      Processor model : Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
      #+END_EXAMPLE
*** Afternoon Session 2:00PM to 4:30 PM
    + Booted Sony 1 TB USB HDD from my laptop
    + Connected to Wifi-router
    + Removed Incoming connection in the lab in switch from where
      all desktop machine gets DHCP IPs.

    + Took one LAN cable and established LAN connection between
      switch and Wi-Fi router
    + Now all desktop machines are getting dhcp ip from wi-fi router
    + 30 machines are now connected to college cloud
    + Around 30 students attended to the college cloud pilot
      test.
    + Used *Problem Solving* lab to show demo
    + Then, We asked students to perform experiments on that lab
    + After 40 minutes, I have started another lab *Data structure* (
      Students choice). That means there are now two labs running in
      college college.
    + Out of 30 students, 26 students were performing experiments on
      two labs
    + We asked students to choose any lab from the running two labs
      *Problem solving* and *Data structures* and perform any
      experiments.
    + Final result, Every student was able to perform any experiment
      from any lab from the two labs mentioned above without any
      loading issue.
    + At around 4:30 PM, we have asked students to submit their
      feedback  on college cloud by providing feedback forms(Hard
      copy)



     






 
   

** Overall College cloud pilot test
   For College Cloud pilot test, I used following system configuration
   #+BEGIN_EXAMPLE
   RAM : 8GB ( 4 GB for Open-edX platform, 4GB for host machine)
   CPUs:4  ( 2 for Open-edX platform, 2 for Host machine( cluster))
   Processor model : Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
   #+END_EXAMPLE
   
   |----------------+------------+-----------+-----------|
   | No.of.Students | No.of.Labs | RAM Usage | CPU usage |
   |----------------+------------+-----------+-----------|
   |         26(30) |          1 |       TBD |       TBD |
   |----------------+------------+-----------+-----------|
   |         26(30) |          2 |       TBD |       TBD |
   |----------------+------------+-----------+-----------|

*** Issues while workshop is going on 
    Feedback link was not working on edX platform.

* Analysis/observations
  - Over the LAN :: 50 students can use College Cloud at a time using
                    the above system configuration for 5 labs. 

                    If we use
		    #+BEGIN_EXAMPLE
		    Processor : Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz   ( Model : intel-db75en)
		    RAM : 16 GB
		    SMPS : 600 W
		    CPUs: 8 four
		    MotherBoard wattage: 77 W
		    #+END_EXAMPLE

		    I am sure, 100-200 students can use College Cloud
                    for 10-20 labs at a time( May be more).  
  - Over the Wi-Fi ::
		     - System configuration 
		       #+BEGIN_EXAMPLE
	               RAM : 8GB ( 4 GB for Open-edX platform, 4GB for host machine)
		       CPUs:4  ( 2 for Open-edX platform, 2 for Host machine( cluster))
		       Processor model : Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
		       #+END_EXAMPLE
                       Max 15-20 students can use the College Cloud.

                     - System Configuration  
		       #+BEGIN_EXAMPLE
		       Processor : Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz   ( Model : intel-db75en)
		       RAM : 16 GB
		       SMPS : 600 W
		       CPUs: 8 four
		       MotherBoard wattage: 77 W
		       #+END_EXAMPLE
		       (*Assumption*) Max 60-80 students can use College Cloud at a
                       time

* Post Work shop
  - Once we reach VLEAD, IIITH, Hyderabad, I have checked why feedback
    link was not working?
  - Solution :: That was my mistake. I have loaded up different
                vagrant box instead of working one. We had 4-5 vagrant
                boxes in College cloud.

* Conclusion
  As we expected, we are successfully completed pilot test using
  college cloud.  My observation is, College Cloud should run on LAN
  in order to achieve 100-200 users for 10-20 labs at a time. Over the
  Wifi only 20-30 students/lab users can use 3-5 labs at a time, it
  very low as we know.
