#+Title: Workshop at Vardhaman College of Engineering
#+DATE: [2017-04-06 Thu]

* Introduction
  The Documents contains the workshop details conducted at Vardhaman
  College of Engineering.

* Workshop Schedule and Venue
  - Venue :: Vardhaman College of Engineering, Hyderabad
  - Date :: [2017-04-06 Thu]
  - Time :: 14:30 to 17:00
* Team From VLEAD
  Siva Shanker, Raghupathi Ravi Kiran and Lalit

* Summary of the Workshop  
  Siva, Raghupathi Ravi Kiran and I went to Vardhaman Engg College for
  conducting workshop. We started with a demo of Online version and
  moved to College Cloud.  We had both versions running as there were
  constraints of bandwidth.

  There were 30 students from ECE, CSE and IT and 2 Faculty from Mech
  and ECE.

** What was happened in Vardhaman Engineering College?
   There were around 30 participants.  There were three connections to
   access the labs
   1. Two Wi-Fis, College Wifi which has Internet access and College
      Cloud Wi-Fi which has no Internet access.  Due to College Wi-fi
      was very slow, even for 5 users/participants, labs/any other
      websites were not loading faster.  During the slides
      presentation, Lalit has connected to College Wi-fi to show our
      labs on online. we have seen loading issue, so thought of using
      College Cloud edition. We enabled College Cloud for the demo.
 
   2. There is a LAN connection also,


Now, the students have chance of choosing any one from three available
choices. So, initially all of them are connected to their own college
wifi which was not working properly for all of them at a time.
** Following are some of the observations

   1) Some of the labs did not load (image processing and problem
      solving) for online version.  Action item - Lalit will prepare a
      rubic for identification of working labs and will contact Virtual
      Labs participating institutes to identify those labs and prepare a
      consolidated list.  Will send an email and have the list ready by
      Apr 17th.
   
   2) On college cloud - labs that are deployed for use were not opening
      consistently for users including Feedback form. Ravi Shankar garu,
      Maruthi Rao garu to have a meeting on this tomorrow(Apr 7) to
      discuss on College Cloud with Professor Venkatesh sir. An action
      plan will emerge after the meeting.  This could include removal of
      Wifi router as DHCP, forum for interacting with participants of
      College Cloud Workshop held @ IIIT-Hyd on Mar 15, etc

   3) Understand the need and removal of labs that are in "in
      progress/under construction" from open edX.  Priya, Ravi Garu and
      Lalit to discuss on this.

   4) Usability for accessing labs has been a struggle. Lalit to reach
      out Usability team on this again !


   5) The feedback has been mixed, we also collected physical copy of
      feedback form as the online feedback form was not completed.


   Then,some them are connected to College Cloud wi-fi which supports
   only for 10-15 users/participants but there were 30 participants which
   is not suitable over wifi ( as we know) to access the labs.


1) For feedback, yes it was loading very slowly. Because even lab's
   experiments were also loading slowly.

2) If they are more than 10 lab users are using labs over the Wifi,
   labs will not be loading very fast on both online and offline. It
   depends on Internet bandwidth speed.
  
** Issues with Internet Bandwidth speed 
*** Online version ( Internet):
    1. Reasons for Image processing labs and problem solving and even data
       structures lab too, are,

       Following could be factors,
       1. Institute/College Overall Internet Speed
       2. Internet speed in the computers lab that has given to us for the
	  workshop by the college.
       3. How participants are accessing the labs( Over Wifi or LAN),
	   1. If They use LAN, Labs would load properly.
	   2. If they use Wifi, again accessing the labs depends on wifi
              signal strength here.

    2. Above two labs were working in previous three workshops( GMRIT,
       Matrusri and MJCET).
*** Offline Version
    1. Workshop participants have to use LAN, then only we will not face
       above problems( As said by Mr. Lalit).  Based on previous workshops
       i am mentioning this point here. We have not faced Issue with
       loading three above labs in previous workshop.
    2. If they use Wifi, max 10-15 labs can be accessed by the lab users.
       Unfortunately, This is what happened at Vardhaman College, in
       Vardhman College, desktop computers are supporting wifi( desktop
       computers are able connect to WiFi.

       Most of the colleges would not be having this advantage, so, in
       this case, they will be using LAN. Then there will not be "labs are
       not loading properly or slowly issue.


